# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 601)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 871, 601))
        self.frame.setStyleSheet("background-color: #ffffff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 90, 354, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setStyleSheet("font-weight: 700;\n"
"font-size:38px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(620, 450, 101, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 127, 255);\n"
"    border-radius: 10px;\n"
"    color:#ffffff;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 181, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 127, 255); */\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(100, 160, 251, 271))
        self.frame_2.setStyleSheet("background-color: #f1ffbe;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 199, 149))
        self.label_6.setStyleSheet("image: url(__pycache__/boba.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 181, 35))
        self.label_5.setStyleSheet("font: 16pt \"RED BURGER\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(70, 220, 101, 35))
        self.label_12.setStyleSheet("font: 13pt \"RED BURGER\";")
        self.label_12.setObjectName("label_12")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 520, 47, 13))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(400, 520, 101, 25))
        self.label_3.setStyleSheet("color:rgb(156, 156, 156);\n"
"font-size:12px;")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 548, 881, 61))
        self.label_7.setStyleSheet("background-color: #f1ffbe;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 440, 160, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setStyleSheet("image: url(__pycache__/silang.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: rgb(75, 75, 75);\n"
"font-size: 15px;\n"
"text-decoration:underline;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   color: rgb(179, 179, 179); /* Warna latar belakang saat hover */\n"
"}\n"
"\n"
"/* QPushButton Pressed State */\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 0, 0); /* Warna latar belakang saat tombol ditekan */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(530, 400, 111, 35))
        self.label_9.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 200, 361, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setStyleSheet("background-color:#dde8ff;\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:15px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setStyleSheet("background-color:#dde8ff;\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:15px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setStyleSheet("background-color:#dde8ff;\n"
"border:none;\n"
"border-bottom:1px solid rgba(105,118,132,255);\n"
"padding-bottom:5px;\n"
"font-size:15px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setStyleSheet("background-color:#ffffff;\n"
"border:none;\n"
"font-size:15px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_3.addWidget(self.dateTimeEdit)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 881, 61))
        self.label_10.setStyleSheet("background-color: #f1ffbe;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 69, 111, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("image: url(__pycache__/kembali.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(460, 390, 61, 35))
        self.label_11.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_11.setObjectName("label_11")
        self.frame_2.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_9.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_10.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label_11.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Pesan"))
        self.label_5.setText(_translate("Form", "Brown Sugar Boba"))
        self.label_12.setText(_translate("Form", "Rp. 18.000,00"))
        self.label_3.setText(_translate("Form", "By Ahmed Jhordy"))
        self.pushButton_2.setText(_translate("Form", "Batakan Pesanan"))
        self.label_9.setText(_translate("Form", "Rp. 18.000,00"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Pemesan"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Deskripsi (formal)"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Penjual"))
        self.lineEdit_6.setText(_translate("Form", "Waktu:"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "waktu"))
        self.pushButton_3.setText(_translate("Form", "Kembali"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Total :</span></p></body></html>"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
